### ISSUE TITLE
AA not kicking in with Gradle 4.1 and Gradle Android Plugin Version 3.0-alpha 5

### ISSUE THREAD

**Issue by kashban** [androidannotations/androidannotations#2024] opened 2017-07-09 07:19 UTC
**AndroidAnnotations version**:

4.3.1

**Android compile SDK version**:

25

**Annotated code**:
Several classes but AA is not generating anything at all.

My build.gradle:
```

buildscript {
    repositories {
        mavenCentral()
        mavenLocal()
        jcenter()
    }
}

apply plugin: 'com.android.application'
//apply plugin: 'com.neenbedankt.android-apt'
def AAVersion = '4.3.1'
def GooglePlayVersion = '11.0.2'
def AndroidSupportVersion = '25.4.0'
def CompileSdkVersion = 25

ext.androidAnnotationsVersion = '4.3.1';

configurations {
    apt
    implementation.exclude group: "org.apache.httpcomponents", module: "httpclient"
}


android {
    dataBinding {
        enabled=true
    }

    flavorDimensions "production", "debug"

    signingConfigs {
        release {
            storeFile file("../AndroidKeyStore")
            storePassword "xxx"
            keyAlias "juergenwahlmann"
            keyPassword "xxx"
            v2SigningEnabled false
        }
        debug {
            storeFile file("../AndroidKeyStore")
            storePassword "xxx"
            keyAlias "juergenwahlmann"
            keyPassword "xxx"
            v2SigningEnabled false
        }
    }
    compileSdkVersion 25
    buildToolsVersion '26.0.0'
    defaultConfig {
        applicationId 'de.kashban.android.picturecalendar'
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 317
        versionName '3.1.7'
        multiDexEnabled true

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["logLevel": "TRACE",
                             "logAppenderConsole": "true",
                             "resourcePackageName": android.defaultConfig.applicationId
                             ]
                //className 'org.androidannotations.androidannotations'
            }
        }
        signingConfig signingConfigs.debug
    }

    useLibrary 'org.apache.http.legacy'

    // AA: if you are going to use the spring rest template with AA
    packagingOptions {
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/notice.txt'
    }
    productFlavors {
        production {
            applicationId = 'de.kashban.android.picturecalendar'
            minSdkVersion 19
            signingConfig signingConfigs.release
            targetSdkVersion 25
            dimension 'production'
        }
        development {
            applicationId = 'de.kashban.android.picturecalendar'
            minSdkVersion 19
            signingConfig signingConfigs.debug
            dimension 'debug'
        }
    }

    buildTypes.debug {
        minifyEnabled false
        shrinkResources false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
    }

    buildTypes.release {
        minifyEnabled true
        shrinkResources true
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // AA imports (also enables REST support w AA)!!
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
    implementation "org.androidannotations:androidannotations-api:$AAVersion"
    implementation 'com.google.http-client:google-http-client-jackson2:1.20.0'
    implementation 'com.google.apis:google-api-services-drive:v2-rev171-1.20.0'
    implementation "com.google.android.gms:play-services-auth:$GooglePlayVersion"
    implementation "com.google.android.gms:play-services-identity:$GooglePlayVersion"
    implementation "com.google.android.gms:play-services-plus:$GooglePlayVersion"
    implementation "com.google.android.gms:play-services-base:$GooglePlayVersion"
    implementation "com.google.android.gms:play-services-analytics:$GooglePlayVersion"
    implementation "com.google.android.gms:play-services-drive:$GooglePlayVersion"
    implementation "com.google.android.gms:play-services-ads:$GooglePlayVersion"
    implementation 'com.google.apis:google-api-services-analytics:v2.4-rev93-1.20.0'
    implementation('com.google.api-client:google-api-client-android:1.18.0-rc') {
        exclude group: 'xpp3'
        exclude group: 'com.google.android.google-play-services'
        exclude group: 'org.apache.httpcomponents'
        exclude group: 'com.google.android'
    }
    implementation('com.google.http-client:google-http-client:1.18.0-rc') {
        exclude group: 'xpp3'
        exclude group: 'com.google.android.google-play-services'
        exclude group: 'org.apache.httpcomponents'
        exclude group: 'com.google.android'
    }
    implementation "com.android.support:support-v4:$AndroidSupportVersion"
    implementation "com.android.support:support-v13:$AndroidSupportVersion"
    implementation "com.android.support:appcompat-v7:$AndroidSupportVersion"
    implementation "com.android.support:gridlayout-v7:$AndroidSupportVersion"
    implementation "com.android.support:cardview-v7:$AndroidSupportVersion"
    implementation "com.android.support:palette-v7:$AndroidSupportVersion"
    implementation "com.android.support:design:$AndroidSupportVersion"
    implementation "com.android.support:recyclerview-v7:$AndroidSupportVersion"
    implementation 'com.android.support:multidex:1.0.1'
    implementation 'com.patrickpissurno:ripple-effect:1.3.1'
    implementation 'com.afollestad.material-dialogs:core:0.9.4.4'
    implementation 'com.github.jrejaud:ViewPagerIndicator2:0.0.2'
    implementation project(':pictureCalendarLibrary')
    implementation project(':aFileChooser')
    //implementation 'andhradroid.dev:aFilechooser:1.0.1'
    implementation 'com.github.yukuku:ambilwarna:2.0.1'
    implementation 'com.github.androidquery:androidquery:0.26.9'
    implementation 'com.github.piruin:quickaction:2.3'
    implementation 'com.github.jayschwa:AndroidSliderPreference:v1.0.0'
    implementation 'com.daimajia.easing:library:2.0@aar'
    implementation 'com.daimajia.androidanimations:library:2.2@aar'
    implementation 'com.github.castorflex.smoothprogressbar:library:1.0.0'
    implementation 'com.makeramen:roundedimageview:2.2.1'
    implementation('com.mikepenz:aboutlibraries:5.9.6@aar') {
        transitive = true
    }
    implementation 'com.github.nirhart:parallaxscroll:1.0'
    implementation 'com.readystatesoftware.systembartint:systembartint:1.0.3'
    implementation 'com.jayway.android.robotium:robotium-solo:5.6.3'
    implementation 'uk.co.chrisjenx:calligraphy:2.2.0'
    implementation 'com.dmitrymalkovich.android:material-design-dimens:1.4'
}

def getSourceSetName(variant) {
    return new File(variant.dirName).getName();
}

android.applicationVariants.all { variant ->
    def aptOutputDir = project.file("build/source/apt")
    def aptOutput = new File(aptOutputDir, variant.dirName)
    println "****************************"
    println "variant: ${variant.name}"
    println "manifest:  ${variant.outputs[0].processResources.manifestFile}"
    println "aptOutput:  ${aptOutput}"
    println "****************************"

    android.sourceSets[getSourceSetName(variant)].java.srcDirs+= aptOutput.getPath()

    variant.javaCompiler.options.compilerArgs += [
            '-processorpath', configurations.apt.getAsPath(),
            '-AandroidManifestFile=' + variant.outputs[0].processResources.manifestFile,
            '-s', aptOutput
    ]

    variant.javaCompiler.source = variant.javaCompiler.source.filter { p ->
        return !p.getPath().startsWith(aptOutputDir.getPath())
    }

    variant.javaCompiler.doFirst {
        aptOutput.mkdirs()
    }
}
```

**Expected generated code**:
Generated Classes in class path

**Actual generated code**:
Nothing

**compiler.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="CompilerConfiguration">
    <wildcardResourcePatterns>
      <entry name="!?*.java" />
      <entry name="!?*.form" />
      <entry name="!?*.class" />
      <entry name="!?*.groovy" />
      <entry name="!?*.scala" />
      <entry name="!?*.flex" />
      <entry name="!?*.kt" />
      <entry name="!?*.clj" />
    </wildcardResourcePatterns>
    <annotationProcessing>
      <profile default="true" name="Default" enabled="true" >
		<processorPath useClasspath="true" />
	  </profile>
    </annotationProcessing>
  </component>
</project>
```
I migrated from APT to Android Annotation Processor to make use of the newer Gradle build system. 

As far as I can tell the Annotation Processor is not activated at all because I don't see any generated classes in my project. 

Databinding Processing seems to work. If I set a className for the annotation processor in my build.gradle at least I get a message that it could not be found (because I don't know the exact class name for org.androidannotations). 

Any hints?

**Comment by WonderCsabo** [comment] 2017-07-10 08:08
I cannot reproduce this issue. See the example project [here](https://github.com/WonderCsabo/androidannotations/tree/2024_example/examples/gradle).

Please not that if AA is not getting called, we cannot do anything from AA side. It indicates there is an issue with the build system configuration.

**Comment by kashban** [comment] 2017-07-10 19:08
I guess you're right, but what might that be? I followed all instructions by the book.

**Comment by wintersandroid** [comment] 2017-07-10 23:58
I am using the same gradle plugin, and it works fine. I only have 
`dependencies {
    annotationProcessor "org.androidannotations:androidannotations:${rootProject.ext.androidAnnotationsVersion}"
    compile "org.androidannotations:androidannotations-api:${rootProject.ext.androidAnnotationsVersion}"
`

I dont have any of the stuff in application variants. I remember ditching that configuration a while ago, I think it was necessary with the annotationProcessor but not any longer)

**Comment by WonderCsabo** [comment] 2017-07-11 06:52
I suggest to expand my project with the stuff you have incrementally until
it breaks, to find out what is causing the problem.

**Comment by Pascal66** [comment] 2017-07-16 07:00
Same problem with AndroidAnnotations version with or without def AA:
4.3.1
Android Studio 3.0 canary 6 compile SDK version:
26
**Expected generated code**: Generated Classes in class path
**Actual generated code**: Nothing

**Comment by WonderCsabo** [comment] 2017-07-16 07:30
Please check my example project, it does work with those versions. https://github.com/WonderCsabo/androidannotations/tree/2024_example/examples/gradle

**Comment by Pascal66** [comment] 2017-07-16 07:43
example use *-api 
faq say [no](https://github.com/androidannotations/androidannotations/wiki/FAQ#wiki-nothing-generated)
i removed -api build folder and now everything work

**Comment by WonderCsabo** [comment] 2017-07-16 07:45
You have to add both dependencies. androidannotations.jar ask the processor
and androidannotations-api.jar as a normal dependency.

**Comment by Pascal66** [comment] 2017-07-16 07:52
work well like that:
`dependencies {
implementation "com.android.support:appcompat-v7:26.0.0-beta2"
annotationProcessor "org.androidannotations:androidannotations:4.3.1"
implementation "org.androidannotations:androidannotations:4.3.1"
}`

**Comment by WonderCsabo** [comment] 2017-07-16 07:53
Yes, this is correct.

**Comment by dodgex** [comment] 2017-07-16 09:59
actually the implementation dependency should be `"org.androidannotations:androidannotations-api:4.3.1" ` otherwise you put the whole annotation processor code into your app

like so:
```
dependencies {
    implementation "com.android.support:appcompat-v7:26.0.0-beta2" 
    annotationProcessor "org.androidannotations:androidannotations:4.3.1" 
    implementation "org.androidannotations:androidannotations-api:4.3.1" 
}
```

**Comment by WonderCsabo** [comment] 2017-07-16 17:31
I am sorry @Pascal66, @dodgex is right! I missed that when looking at your code on mobile. You should correct otherwise you package all the processor code to the APK.

**Comment by Pascal66** [comment] 2017-07-16 17:48
Ok, i'll try, but the only way I found to generate classes was to not use -api.
gradle:3.0.0-alpha6 not maven

**Comment by WonderCsabo** [comment] 2017-07-18 10:43
@Pascal66 again, check the example project, it works well.
https://github.com/WonderCsabo/androidannotations/tree/2024_example/examples/gradle

**Comment by kashban** [comment] 2017-07-18 11:40
Thanks for the discussion, I will try again after ironing out some other aspects of my app for a new version.

**Comment by WonderCsabo** [comment] 2017-07-18 13:22
I am closing this issue now, since it is not an AA error, but a project configuration problem. Feel free to reopen / discuss further if there is anything useful to add.

**Closed by WonderCsabo** 2017-07-18 13:22 UTC

**Comment by kashban** [comment] 2017-08-14 06:11
Thanks. I will return to migrate to the new gradle plugin in a short while from now and check this out. This discussion was very refreshing.
