### ISSUE TITLE
java.lang.IllegalArgumentException: uSource failed: U_ILLEGAL_ARGUMENT_ERROR

### ISSUE THREAD

**Issue by richardjbs** [androidannotations/androidannotations#2127] opened 2018-03-16 21:27 UTC
**AndroidAnnotations version**: 4.4.0

**Android compile SDK version**: 27

**Annotated code**:
```java
@Rest(rootUrl = API_URL, converters = {GsonHttpMessageConverter.class, FormHttpMessageConverter.class}, interceptors = AuthInterceptor.class,
        responseErrorHandler = MSAuthenticationResponseErrorHandler.class, requestFactory = MSHttpRequestFactory.class)
@Accept(MediaType.APPLICATION_JSON)
public interface MSRestClient extends RestClientErrorHandling, RestClientHeaders
```

**Actual generated code**:
```java
@Accept("application/json")
public final class MSRestClient_
    implements MSRestClient
{
    private HttpAuthentication authentication;
    private HashMap<String, String> availableCookies;
    private HashMap<String, String> availableHeaders;
    private RestErrorHandler restErrorHandler;
    private String rootUrl;
    private RestTemplate restTemplate;

    public MSRestClient_(Context context) {
        availableCookies = new HashMap<String, String>();
        availableHeaders = new HashMap<String, String>();
        rootUrl = "our API url"; // removed for privacy concerns
        restTemplate = new RestTemplate(); // <- crash happens in here
        restTemplate.getMessageConverters().clear();
        restTemplate.getMessageConverters().add(new GsonHttpMessageConverter());
        restTemplate.getMessageConverters().add(new FormHttpMessageConverter());
        restTemplate.setInterceptors(new ArrayList<ClientHttpRequestInterceptor>());
        restTemplate.getInterceptors().add(AuthInterceptor_.getInstance_(context));
        restTemplate.setRequestFactory(MSHttpRequestFactory_.getInstance_(context));
        restTemplate.setErrorHandler(MSAuthenticationResponseErrorHandler_.getInstance_(context));
    }
```

**Stacktrace in case of AA crash**:
Fatal Exception: java.lang.IllegalArgumentException: uSource failed: U_ILLEGAL_ARGUMENT_ERROR
       at libcore.icu.NativeConverter.encode(NativeConverter.java)
       at java.nio.charset.CharsetEncoderICU.implFlush(CharsetEncoderICU.java:142)
       at java.nio.charset.CharsetEncoder.flush(CharsetEncoder.java:668)
       at java.util.zip.ZipCoder.getBytes(ZipCoder.java:96)
       at java.util.zip.ZipFile.getEntry(ZipFile.java:316)
       at java.util.jar.JarFile.getEntry(JarFile.java:234)
       at libcore.io.ClassPathURLStreamHandler.findEntryWithDirectoryFallback(ClassPathURLStreamHandler.java:100)
       at libcore.io.ClassPathURLStreamHandler.getEntryUrlOrNull(ClassPathURLStreamHandler.java:60)
       at java.lang.VMClassLoader.getResources(VMClassLoader.java:82)
       at java.lang.BootClassLoader.findResources(ClassLoader.java:1357)
       at java.lang.BootClassLoader.getResources(ClassLoader.java:1414)
       at java.lang.ClassLoader.getResources(ClassLoader.java:827)
       at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:341)
       at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:442)
       at java.nio.charset.Charset$1.getNext(Charset.java:377)
       at java.nio.charset.Charset$1.hasNext(Charset.java:392)
       at java.nio.charset.Charset$3.run(Charset.java:642)
       at java.nio.charset.Charset$3.run(Charset.java:632)
       at java.security.AccessController.doPrivileged(AccessController.java:41)
       at java.nio.charset.Charset.availableCharsets(Charset.java:630)
       at org.springframework.http.converter.StringHttpMessageConverter.(SourceFile:66)
       at org.springframework.http.converter.StringHttpMessageConverter.(SourceFile:56)
       at org.springframework.web.client.RestTemplate$DefaultMessageConverters.init(SourceFile:779)
       at org.springframework.web.client.RestTemplate.(SourceFile:157)
       at com.ms.app.rest.MSRestClient_.(SourceFile:57)
       at com.ms.app.content.MSPresetCommunicator_.init_(SourceFile:35)
       at com.ms.app.content.MSPresetCommunicator_.getInstance_(SourceFile:28)
       at com.ms.app.content.UPContentManager_.init_(SourceFile:49)
       at com.ms.app.content.UPContentManager_.getInstance_(SourceFile:39)
       at com.ms.app.content.pr.PManager_.init_(SourceFile:57)
       at com.ms.app.content.pr.PManager_.getInstance_(SourceFile:45)
       at com.ms.app.MSApplication$1.run(SourceFile:151)
       at java.lang.Thread.run(Thread.java:762)

**Comment by dodgex** [comment] 2018-06-09 18:29
This issue is not caused by, or related to AndroidAnnotations. 

This is most likely a Android Framework issue.

The call to [`new RestTemplate();`](https://github.com/spring-projects/spring-android/blob/master/spring-android-rest-template/src/main/java/org/springframework/web/client/RestTemplate.java#L156) you marked as the cause of the issue is where we leave AndroidAnnotation related code. And if we follow the stacktrace we see that on [line 66 of StringHttpMessageConverter](https://github.com/spring-projects/spring-android/blob/master/spring-android-rest-template/src/main/java/org/springframework/http/converter/StringHttpMessageConverter.java#L66) we leave spring for android and enter platform code.

I'm pretty sure that this if you call  `Charset.availableCharsets().values()` anywhere in your code you'll see the same exception. you should consider raising an issue in the Android bug tracker

**Closed by dodgex** 2018-06-09 18:29 UTC
