### ISSUE TITLE
RunTimeException for Android Api 21 and 22

### ISSUE THREAD

**Issue by juanvillaamaro** [androidannotations/androidannotations#1951] opened 2017-02-02 14:17 UTC
Hi everyone, I have a problem when I'm trying to generate a signed apk for android lollipop(Api 21,22), the log says that "couldn't find Application_ class" but in api 23 or higher it works, besides Application_ class exist because when I compile directly from android Studio to the Lollipop divice, everything works, but when I generate a signed application everything crash without start.

**AndroidAnnotations version**:
     4.2.0
**Android compile SDK version**:
    25

**Build tools**
```ruby
...
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

        defaultConfig {
        applicationId "amaro.amaroandroid"
        minSdkVersion 21
        targetSdkVersion 25
        renderscriptTargetApi 25
        renderscriptSupportModeEnabled true
        versionCode 2
        versionName "1.0 beta.0.1"
        //Instrumentation Test Runner
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        // Enabling multidex support.
        multiDexEnabled true
        manifestPlaceholders = [manifestApplicationId          : "${applicationId}",
                                onesignal_app_id               : "xxx",
                                onesignal_google_project_number: "1234"]
        vectorDrawables.useSupportLibrary = true
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}
...
```

**Manifest**:
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="amaro.amaroandroid">

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.CALL_PHONE"/>
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
    <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_LOGS"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.READ_SMS"/>
    <uses-permission android:name="android.permission.REORDER_TASKS"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <application
        android:name=".AmaroApp_"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher_circle"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity
            android:name=".Areas.Splash.SplashActivity_"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>
                <category android:name="android.intent.category.DEFAULT"/>
            </intent-filter>
        </activity>
        <activity
            android:name=".Areas.Main.MainActivity_"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar">
        </activity>
        <activity
            android:name=".Areas.Products.Catalog.CatalogActivity_"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.SEARCH"/>
            </intent-filter>
        </activity>
        <activity
            android:name=".Areas.GuideShops.GuideshopsActivity_"
            android:label="@string/title_activity_guideshops"
            android:screenOrientation="portrait">
        </activity>
        <activity
            android:name=".Areas.CheckOut.CartActivity_"
            android:label="@string/title_activity_cart"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar"
            android:windowSoftInputMode="adjustPan">
        </activity>
        <activity
            android:name=".Areas.Login.LoginActivity_"
            android:label="@string/title_activity_login"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar"
            android:windowSoftInputMode="adjustPan">
        </activity>
        <activity
            android:name=".Areas.Login.SignInActivity_"
            android:label="@string/title_activity_sign_in"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar"
            android:windowSoftInputMode="adjustPan">
        </activity>
        <activity
            android:name=".Areas.Products.Details.ProductDetailsActivity_"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar"
            android:windowSoftInputMode="adjustResize">
        </activity>
        <activity
            android:name=".Areas.CheckOut.CheckoutActivity_"
            android:label="@string/title_activity_checkout"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar"
            android:windowSoftInputMode="adjustPan">
        </activity>
        <activity
            android:name=".Areas.Account.AccountActivity_"
            android:label="@string/title_activity_account"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar">
        </activity>
        <activity
            android:name=".Areas.Account.Orders.OrdersActivity_"
            android:label="@string/title_activity_orders"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar">
        </activity>
        <activity
            android:name=".Areas.Account.Register.RegisterActivity_"
            android:label="@string/title_activity_register"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar">
        </activity>
        <activity
            android:name=".Areas.Account.Orders.OrderDetailsActivity_"
            android:label="@string/title_activity_order_details"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar">
        </activity>
        <activity
            android:name=".Areas.Account.Orders.TrackingActivity_"
            android:label="@string/title_activity_tracking"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar">
        </activity>
        <activity
            android:name=".Areas.Account.Help.HelpMailActivity_"
            android:label="@string/title_activity_help_mail"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar">
        </activity>
        <activity
            android:name=".Areas.Account.Help.FaqActivity_"
            android:label="@string/title_activity_faq"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar">
        </activity>
        <!-- [START gcm_receiver] -->
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>

                <category android:name="amaro.amaroandroid"/>
            </intent-filter>
        </receiver>
        <!--
             The API key for Google Maps-based APIs is defined as a string resource.
             (See the file "res/values/google_maps_api.xml").
             Note that the API key is linked to the encryption key used to sign the APK.
             You need a different API key for each encryption key, including the release key that is used to
             sign the APK for publishing.
             You can define the keys for the debug and release targets in src/debug/ and src/release/. 
        -->
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/google_maps_key"/>
        <meta-data
            android:name="io.fabric.ApiKey"
            android:value="xxx"/>

        <service
            android:name=".Utils.Push.AmaroNotificationExtenderService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.onesignal.NotificationExtender"/>
            </intent-filter>
        </service>
        <!--
 ATTENTION: This was auto-generated to add Google Play services to your project for
     App Indexing.  See https://g.co/AppIndexing/AndroidStudio for more information.
        -->
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version"/>

        <activity android:name=".Areas.GuideShops.GuideShopsWebviewActivity_"
                  android:theme="@style/AppTheme.NoActionBar"
                  android:screenOrientation="portrait">
        </activity>
    </application>

</manifest>
```

**Code**:
```java
@EApplication
public class AmaroApp extends MultiDexApplication {
  @Bean
  RSRestErrorHandler errorHandler;

  Gson gson = new Gson();
  SharedPreferences settings;

  public static Context getAppContext() {
    return AmaroApp_.getInstance();
  }

  @Override
  public void onCreate() {
    super.onCreate();
    settings = getSharedPreferences("menu", Context.MODE_PRIVATE);
    AmaroServices.initializeServices(this, errorHandler);
    ZopimChatApi.init(getResources().getString(R.string.ZopimKey));
    OneSignal.startInit(this)
        .setNotificationOpenedHandler(new AmaroNotificationOpenedHandler())
        .setNotificationReceivedHandler(new AmaroNotificationReceivedHandler())
        .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification).init();
    Fabric.with(this, new Crashlytics());
  }


  @Override
  protected void attachBaseContext(Context base) {
    MultiDex.install(base);
    super.attachBaseContext(base);
  }


  @Background
  public void setMenu(Activity activity) {
    getMenu(AmaroServices.getMenu().getMenuObject(), activity);
  }

  @UiThread
  public void getMenu(MenuResponse response, Activity activity) {
    if (response != null) {
      String lastMenu = settings.getString("menu", "");
      String newMenu = gson.toJson(response);
      //Compare Fields in Order to validate that none of the are empty

      if (!lastMenu.equals(newMenu) && activity instanceof CatalogActivity) {
        String menuString = gson.toJson(response);
        SharedPreferences.Editor editor = settings.edit();
        editor.putString("menu", menuString);
        editor.commit();
        AmaroServices.setMenuApp(response);
        ((CatalogActivity) activity).mainCategory = response.getData().iterator().next().getName();
        ((CatalogActivity) activity).setSlideMenu();
      }
    }
  }

  public void onActivityResumed(Activity activity) {
    if (activity instanceof CatalogActivity) {

      AmaroServices.getMyAccount().setCookie(amaro.api.BuildConfig.AUTHENTICATION, getSharedPreferences(amaro.api.BuildConfig.AUTHENTICATION, Context.MODE_PRIVATE).getString(amaro.api.BuildConfig.AUTHENTICATION, ""));
      AmaroServices.getMyAccount().setCookie(amaro.api.BuildConfig.SESSION, getSharedPreferences(amaro.api.BuildConfig.AUTHENTICATION, Context.MODE_PRIVATE).getString(amaro.api.BuildConfig.SESSION, ""));

      AmaroServices.getMyCart().setCookie(amaro.api.BuildConfig.AUTHENTICATION, getSharedPreferences(amaro.api.BuildConfig.AUTHENTICATION, Context.MODE_PRIVATE).getString(amaro.api.BuildConfig.AUTHENTICATION, ""));
      AmaroServices.getMyCart().setCookie(amaro.api.BuildConfig.SESSION, getSharedPreferences(amaro.api.BuildConfig.AUTHENTICATION, Context.MODE_PRIVATE).getString(amaro.api.BuildConfig.SESSION, ""));

      AmaroServices.getMyCheckOut().setCookie(amaro.api.BuildConfig.AUTHENTICATION, getSharedPreferences(amaro.api.BuildConfig.AUTHENTICATION, Context.MODE_PRIVATE).getString(amaro.api.BuildConfig.AUTHENTICATION, ""));
      AmaroServices.getMyCheckOut().setCookie(amaro.api.BuildConfig.SESSION, getSharedPreferences(amaro.api.BuildConfig.AUTHENTICATION, Context.MODE_PRIVATE).getString(amaro.api.BuildConfig.SESSION, ""));

      MenuResponse menuClass = gson.fromJson(getSharedPreferences("menu", Context.MODE_PRIVATE).getString("menu", ""), MenuResponse.class);
      AmaroServices.setMenuApp(menuClass);

      ((CatalogActivity) activity).updateDrawerGreedings();
      setMenu(activity);
    }

    if(activity instanceof MainActivity){
      AmaroServices.getMyAccount().setCookie(amaro.api.BuildConfig.AUTHENTICATION, getSharedPreferences(amaro.api.BuildConfig.AUTHENTICATION, Context.MODE_PRIVATE).getString(amaro.api.BuildConfig.AUTHENTICATION, ""));
      AmaroServices.getMyAccount().setCookie(amaro.api.BuildConfig.SESSION, getSharedPreferences(amaro.api.BuildConfig.AUTHENTICATION, Context.MODE_PRIVATE).getString(amaro.api.BuildConfig.SESSION, ""));

      AmaroServices.getMyCart().setCookie(amaro.api.BuildConfig.AUTHENTICATION, getSharedPreferences(amaro.api.BuildConfig.AUTHENTICATION, Context.MODE_PRIVATE).getString(amaro.api.BuildConfig.AUTHENTICATION, ""));
      AmaroServices.getMyCart().setCookie(amaro.api.BuildConfig.SESSION, getSharedPreferences(amaro.api.BuildConfig.AUTHENTICATION, Context.MODE_PRIVATE).getString(amaro.api.BuildConfig.SESSION, ""));

      AmaroServices.getMyCheckOut().setCookie(amaro.api.BuildConfig.AUTHENTICATION, getSharedPreferences(amaro.api.BuildConfig.AUTHENTICATION, Context.MODE_PRIVATE).getString(amaro.api.BuildConfig.AUTHENTICATION, ""));
      AmaroServices.getMyCheckOut().setCookie(amaro.api.BuildConfig.SESSION, getSharedPreferences(amaro.api.BuildConfig.AUTHENTICATION, Context.MODE_PRIVATE).getString(amaro.api.BuildConfig.SESSION, ""));

      MenuResponse menuClass = gson.fromJson(getSharedPreferences("menu", Context.MODE_PRIVATE).getString("menu", ""), MenuResponse.class);
      AmaroServices.setMenuApp(menuClass);

      ((MainActivity) activity).updateDrawerGreedings();
      ((MainActivity)activity).setCartItems();
    }
  }

  public void onActivityComeBack(Activity activity) {
    if (activity == null) {
      SplashActivity_.intent(getBaseContext()).flags(Intent.FLAG_ACTIVITY_NEW_TASK).start();
    }
  }

}
```

**Stacktrace in case of AA crash**:
```Java
java.lang.RuntimeException: Unable to instantiate application amaro.amaroandroid.AmaroApp_: java.lang.ClassNotFoundException: Didn't find class "amaro.amaroandroid.AmaroApp_" on path: DexPathList[[zip file "/data/app/amaro.amaroandroid-1/base.apk"],nativeLibraryDirectories=[/data/app/amaro.amaroandroid-1/lib/x86, /vendor/lib, /system/lib]]
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:566)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:147)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5264)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "amaro.amaroandroid.AmaroApp_" on path: DexPathList[[zip file "/data/app/amaro.amaroandroid-1/base.apk"],nativeLibraryDirectories=[/data/app/amaro.amaroandroid-1/lib/x86, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:979)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:561)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534) 
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:147) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5264) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695) 
                                                   	Suppressed: java.lang.NoClassDefFoundError: amaro.amaroandroid.AmaroApp_
                                                       at dalvik.system.DexFile.defineClassNative(Native Method)
                                                       at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                       at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                       at dalvik.system.DexPathList.findClass(DexPathList.java:321)
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                       		... 14 more
                                                   	Suppressed: java.lang.ClassNotFoundException: amaro.amaroandroid.AmaroApp_
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
```

**Comment by dodgex** [comment] 2017-02-02 14:26
Hey, this looks very similar to https://github.com/androidannotations/androidannotations/issues/1946. There it was some kind of issue with multidex and/or old build tools. but as you are using the latest tools already I'm not yet sure what your problem is... do you need multidex? could you try to disable it and check if the `amaro.amaroandroid.AmaroApp_` is found then?

**Comment by WonderCsabo** [comment] 2017-02-02 14:27
The problem is that the generated application class most likely is missing from the main dex file when using legacy multidex. From Lollipop and later, a new version of multidex is used which does not suffer from these kind of issues. But is see that you are seeing this issues with Lollipop... Strange.

Are you sure you are using the latest sdk tools etc? I see that you are using the latest build tools. Also try to build with from command line with Gradle (`./gradlew assembleRelease`).

However, this issue is not strictly AA related.

**Comment by juanvillaamaro** [comment] 2017-02-02 14:30
Thanks, I will do everything and I will let you know if it works in order to close this issue

**Comment by juanvillaamaro** [comment] 2017-02-02 17:44
Solve it!

just add this into your build.

android {
...
dexOptions {
        preDexLibraries = false
        javaMaxHeapSize "4g"
    }
....
}
....
afterEvaluate {
    tasks.matching {
        it.name.startsWith('dex')
    }.each { dx ->
        if (dx.additionalParameters == null) {
            dx.additionalParameters = []
        }
        dx.additionalParameters += '--multi-dex'
        dx.additionalParameters += "--main-dex-list=$projectDir/multidex.keep".toString()
    }
}
....

source
http://stackoverflow.com/questions/26609734/how-to-enable-multidexing-with-the-new-android-multidex-support-library
http://blog.osom.info/2014/10/multi-dex-to-rescue-from-infamous-65536.html

**Comment by dodgex** [comment] 2017-02-02 21:55
Glad to hear that you solved it. And thank you for sharing your solution. 

I'm closing this issue then.

**Closed by dodgex** 2017-02-02 21:55 UTC

**Comment by Bertkiing** [comment] 2017-05-16 06:24
problem exist;
