### ISSUE TITLE
Singleton not initialized correctly while minifyEnabled = true

### ISSUE THREAD

**Issue by namdroid** [androidannotations/androidannotations#2271] opened 2020-05-13 07:24 UTC
**AndroidAnnotations version**:
4.6.0
**Android compile SDK version**:
28
**gradle buildTypes**:

    buildTypes {
        release {
            zipAlignEnabled true
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro', 'proguard-rules-addon-release.pro'
        }
        debug {
            debuggable true
            zipAlignEnabled true
            minifyEnabled false
            useProguard false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'proguard-rules-addon-debug.pro'
        }
    }

**Stacktrace in case of AA crash*
Our AndroidTV App works fine in with debug build but crashs with release build, if minifyEnabled = true. Some variable of initialized EBeans is null. I dont know why. 
We have androidx and gradle plugins 3.6.1. R8 = true. Currently i cant enable proguard in release.
I use proguard config from here: 
https://github.com/androidannotations/androidannotations/wiki/Proguard

it seems the problem of AA ?

**Comment by peshkira** [comment] 2020-05-13 07:46
Can you share the stacktrace you are getting?

Not sure if it is related but I also experience issues with minifyEnabled in 4.6.0 and 4.7.0

```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class my.package.GeneratedFragment_, unresolved supertypes: org.androidannotations.api.bean.BeanHolder, org.androidannotations.api.view.HasViews, org.androidannotations.api.view.OnViewChangedListener
    class my.package.GeneratedFragment_.FragmentBuilder_, unresolved supertypes: org.androidannotations.api.builder.FragmentBuilder
```

**Comment by namdroid** [comment] 2020-05-13 08:23
I dont see any "classes cannot be resolved" in logs

**Comment by WonderCsabo** [comment] 2020-05-13 08:26
@peshkira in your case, it seems the `androidannotations-api` artifact is missing from the classpath. Make sure to add that in the `implementation` configuration.

**Comment by peshkira** [comment] 2020-05-13 08:29
@WonderCsabo Thanks, but it is in there.

```
dependencies {
    def aaVersion = "4.7.0"

    annotationProcessor "org.androidannotations:androidannotations:${aaVersion}"
    implementation "org.androidannotations:androidannotations-api:${aaVersion}"
```

However, once I added your snapshot repository and changed to 4.8.0-SNAPSHOT it works. Do you have an idea?

P.S. sorry to hijack the thread, I can open a new issue

**Comment by WonderCsabo** [comment] 2020-05-13 08:30
@peshkira let's open a new issue then.

**Comment by WonderCsabo** [comment] 2020-05-13 08:32
@namdroid can you:

1. try updating to the latest version of AA?
2. share a small reproducing project if the first point still fails?

**Comment by WonderCsabo** [comment] 2020-11-20 10:55
Closing due to lack fo response

**Closed by WonderCsabo** 2020-11-20 10:55 UTC
