### ISSUE TITLE
Library Builds fail with the new AnnotationsProcessor (gradle plugin 2.3)

### ISSUE THREAD

**Issue by couchcrew-thomas** [androidannotations/androidannotations#1974] opened 2017-03-13 10:08 UTC
**AndroidAnnotations version**: 4.2.0
**Android compile SDK version**: 25
**Referencing Issue**: #1964 

My large app still fails to build with the new `annotationProcessor`, databinding and AA.
I've tried to isolate the error in a demo project. While the demo project fails with a different error than my actual project, it shows that library projects seem to require more configuration than stated in the wiki.

The error I'm getting in the demo project (attached):
`Error:Could not find the AndroidManifest.xml file, using  generation folder [/home/foo/bar/AATest/library/build/generated/source/apt/release])`

In the actual project it fails with `cannot find symbol ...` on any annotated library classes.

[AATest.zip](https://github.com/androidannotations/androidannotations/files/837823/AATest.zip)

**Comment by dodgex** [comment] 2017-03-13 10:11
Thank you for the report! :) I'll try to check this asap.

**Comment by WonderCsabo** [comment] 2017-03-13 21:53
I looked into this, and the problem is the following:

We try to find the manifest file automatically by looking at two locations when the project is using a [Gradle build](https://github.com/androidannotations/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java#L192):

* `build/intermediates/bundles` (worked before for library projects)
* `build/intermediates/manifests/full` (worked before for app projects)

The first path no longer works, because the current variant is `release`, however the folder is called `default`.
The second is never worked for library projects.

However, there is a new folder: `build/intermediates/manifests/aapt`. It seems it uses the correct variant subfolder. We could add this to the list.

**Comment by dodgex** [comment] 2017-03-13 22:12
@WonderCsabo feel free to take over this issue and fix it. you are knowing more about the manifest finder than me.

**Comment by dodgex** [comment] 2017-03-14 18:10
Should be fixed with #1975

**Closed by dodgex** 2017-03-14 18:10 UTC
Labels: Defect
