### ISSUE TITLE
 cannot find symbol class Activity A_ in Android Studio 3.1 with gradle-4.4-all.zip

### ISSUE THREAD

**Issue by VishalThareja** [androidannotations/androidannotations#2155] opened 2018-07-20 12:17 UTC
Not able to find out the class Activity A_ with gradle 4.4.0<br/>
Shows import with red color .

**AndroidAnnotations version:**: - 4.4.0

**Android compile SDK version**: 27

**Gradle code**: 
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
ext.androidAnnotationsVersion = '4.4.0'

android {
    compileSdkVersion 27

    defaultConfig {
        applicationId "com.example.test"
        minSdkVersion 17
        targetSdkVersion 27
        versionCode 4
        versionName "1.2"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true

        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath true
                arguments = ["resourcePackageName": android.defaultConfig.applicationId]
            }
        }

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'proguard-fresco.pro'
        }
    }
    android {
        compileOptions.incremental = false

    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
       

    }

    lintOptions {
        abortOnError false
    }

}

/*configurations {
    annotationProcessor
}*/

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.0'

    annotationProcessor "org.androidannotations:androidannotations:${androidAnnotationsVersion}"
    implementation "org.androidannotations:androidannotations-api:${androidAnnotationsVersion}"

    implementation 'com.android.support:appcompat-v7:27.1.0'
  
    implementation 'com.android.support:support-v4:27.1.0'
    implementation 'com.android.support:design:27.1.0'
    implementation 'com.squareup.retrofit2:retrofit:2.2.0'
    implementation 'com.google.dagger:dagger:2.14.1'
    implementation 'com.google.dagger:dagger-android:2.14.1'
    implementation 'com.google.code.gson:gson:2.7'
    implementation 'com.squareup.okhttp3:okhttp:3.2.0'
    implementation 'com.squareup.okio:okio:1.7.0'
    implementation 'com.squareup.retrofit2:converter-jackson:2.1.0'
    implementation 'com.android.support:recyclerview-v7:27.1.0'
    implementation 'com.github.bumptech.glide:glide:3.7.0'
    implementation 'com.viewpagerindicator:library:2.4.1@aar'
    implementation 'com.google.firebase:firebase-core:10.2.1'
    implementation 'com.google.firebase:firebase-messaging:10.2.1'
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:2.7.22'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:2.2.2'
    androidTestImplementation 'com.android.support.test:runner:0.5'
  
    androidTestImplementation 'com.android.support:support-annotations:25.3.1'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.14.1'
    annotationProcessor 'com.google.dagger:dagger-android-processor:2.14.1'
    compileOnly 'javax.annotation:jsr250-api:1.0'
    implementation 'javax.inject:javax.inject:1'
    implementation 'com.google.dagger:dagger-android-support:2.14.1'
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.4@aar') {
        transitive = true;
    }

}

**Comment by iTruff** [comment] 2018-07-23 18:39
Same, any news about this?

**Comment by khalil2535** [comment] 2018-08-03 18:16
Hello , try this 
File -> Settings -> Build, Execution, Deployment -> Compiler -> Uncheck (Configure on demand)

**Comment by khalil2535** [comment] 2018-09-08 04:15
@nining "android annotations" is dead, last commit was before 3 months so if you need annotations in your code see <a href="https://github.com/JakeWharton/butterknife">butter knife</a>

**Comment by mohamedhamdy-Cis** [comment] 2018-10-17 16:54
any solution for this issue

**Comment by dodgex** [comment] 2018-10-18 12:52
Update to latest verions of AA (4.5.2) and the gradle plugin (3.2.1) and test again, if there are still issues in generation check the build logs. if there are errors or messages you do not understand post them here and we'll try to help. but just saying "cant find _ classes" and/or posting build.gradle does not help very much in finding the issues.

**Comment by hvendrame** [comment] 2018-10-19 19:49
> Update to latest verions of AA (4.5.2) and the gradle plugin (3.2.1) and test again, if there are still issues in generation check the build logs. if there are errors or messages you do not understand post them here and we'll try to help. but just saying "cant find _ classes" and/or posting build.gradle does not help very much in finding the issues.

Hello @dodgex, I can tried change AA 4.5.2 - but it does not exist to gradle.
When I put  AA 4.5.1, I get other error:

16:38:56.149 [Task worker for ':'] ERROR o.a.i.AndroidAnnotationProcessor:249 - Something went wrong: Unexpected error in AndroidAnnotations 4.5.1!
You should check if there is already an issue about it on https://github.com/androidannotations/androidannotations/search?q=java.lang.ClassCastException&type=Issues
If none exists, please open a new one with the following content and tell us if you can reproduce it or not. Don't forget to give us as much information as you can (like parts of your code in failure).
Java version: javac 1.8.0_152-release
Javac processors options: 
Stacktrace: java.lang.ClassCastException: java.lang.String cannot be cast to javax.lang.model.type.DeclaredType
	at org.androidannotations.helper.AnnotationHelper.extractAnnotationClassArrayParameter(AnnotationHelper.java:402)

...
...

Android compile SDK version: 27
Can you help me?

**Comment by dodgex** [comment] 2018-10-20 05:56
Sorry, the AA version was a typo. i meant to write 4.5.1. 

@hvendrame: I need more of the stacktrace to know where the issue comes from. Could you please post the full stacktrace?

**Comment by dodgex** [comment] 2018-10-20 06:02
But from what i cann tell at the moment, it looks like you are using the rest plugin and the issue is related `@Rest` and its `converters` or `interceptors` paramters. could you maybe also post the interfaces where you use `@Rest`?

If  you are afraid it might disclose too many internal information send it to support [[A_T]] androidannotations.org with a small remark that its related to this issue,

**Comment by hvendrame** [comment] 2018-10-20 13:57
@dodgex 
You are a sniper! :D

I checked my interceptors and saw a "error" that Android Studio didn't show , when I arranged. It work fine.

Thanks

**Comment by dodgex** [comment] 2018-10-21 06:33
@hvendrame no problem. =)

As this issue has been lost track of the initial issue and I'm kinda sure that it should be fixed with latest versions I'm closing this issue right now.

**Closed by dodgex** 2018-10-21 06:33 UTC
