### ISSUE TITLE
annotationProcessor, and AndroidAnnotation for library module

### ISSUE THREAD

**Issue by sattha** [androidannotations/androidannotations#1963] opened 2017-03-06 09:48 UTC
**AndroidAnnotations version**: 4.2.0
**Android compile SDK version**: 25

the new annotationProcessor is come with Android Studio 2.3 and Gradle 2.3.0.
I try and it doesn't work. Even, I use apt it still unable to generate code also.

```
def AAVersion = '4.2.0'
annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
compile "org.androidannotations:androidannotations-api:$AAVersion"
```

I have no idea how to configure like this on new annotationProcessor

```
apt {
    arguments {
        library 'true'
   }
}
```

**Stacktrace in case of AA crash**:
Error:Could not find the AndroidManifest.xml file, using  generation folder [/Users/...../core/build/generated/source/apt/prod/debug])

**Comment by dodgex** [comment] 2017-03-07 18:16
like i [asked in the other issue](https://github.com/androidannotations/androidannotations/issues/1964#issuecomment-284808336) could you please provide a sample project where one can reproduce this issue?

**Comment by couchcrew-thomas** [comment] 2017-03-08 11:23
I've created a sample project showing that `android-apt` is now incompatible with google plugins like databinding.

If you try to compile it fails.
When you remove the line `apply plugin: 'android-apt'` it compiles fine.

As you can see, I did not even add androidannotations. `android-apt` is deprecated since 2.3 canary came out and since current and future google plugins will rely on the new annotation processor, androidannotations should use it as well.
[AATest.zip](https://github.com/androidannotations/androidannotations/files/827419/AATest.zip)

**Comment by dodgex** [comment] 2017-03-08 14:14
I'm closing this issue in favor of https://github.com/androidannotations/androidannotations/issues/1964 so that we do not have duplicated communication.

**Closed by dodgex** 2017-03-08 14:14 UTC
