### ISSUE TITLE
Experimental and unsupported 

### ISSUE THREAD

**Issue by mohammedhemaid** [androidannotations/androidannotations#2242] opened 2019-08-21 22:32 UTC
Gradle may disable incremental compilation as the following annotation processors are not incremental: jetified-androidannotations-4.6.0.jar (org.androidannotations:androidannotations:4.6.0).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental

I've put android.enableSeparateAnnotationProcessing=true in the gradle.properties  but it doesn't work 

Note: I use android studio 3.5 with gradle:3.5.0

**Comment by WonderCsabo** [comment] 2019-08-22 07:43
Duplicate of https://github.com/androidannotations/androidannotations/issues/2193 .

**Closed by WonderCsabo** 2019-08-22 07:43 UTC
