### ISSUE TITLE
Annotation doesn't generate class _ - API 26 - Gradle 4.1

### ISSUE THREAD

**Issue by JDSCaram** [androidannotations/androidannotations#2087] opened 2017-11-23 14:37 UTC
Before my project used AndroidAnnotations version 4.3.0 along with gradle 3.5 +
classpath 'com.android.tools.build:gradle:2.2.0'
And everything works perfectly, but I had to upgrade then.

I updated my project to Android API 26 and Gradle 4.1 and AndroidAnnotation 4.5.0-SNAPSHOT. However when I try to run it it can not generate the com class ._
"**error: cannot find symbol class MainActivity_**"

does anyone know what I can be doing wrong? Below my Gradle

**//Gradle Project**

```
buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        // replace with the current version of the Android plugin
        classpath "com.android.tools.build:gradle:3.0.0"
        classpath 'com.google.gms:google-services:3.1.0'
        classpath 'io.fabric.tools:gradle:1.24.4'
    }
}


allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://oss.sonatype.org/content/repositories/ksoap2-android-releases' }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "http://dl.bintray.com/populov/maven" }
        maven { url 'https://repo.spring.io/libs-milestone' }

        mavenLocal()
        mavenCentral()
        google()
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


ext {
    // Version App
    versionCode = 27 
    versionName = "1.25"

    // Sdk and tools
    minSdkVersion = 16
    targetSdkVersion = 26
    compileSdkVersion = 26
    buildToolsVersion = '**26.0.2'**

    // App dependencies
    junitVersion = '4.12'
    runnerVersion = '0.5'
    rulesVersion = '0.5'
    espressoVersion = '2.2.2'
    mockitoVersion = '1.10.19'
    hamcrestVersion = '1.3'
    supportLibraryVersion = '26.1.0'
    aaVersion = '4.5.0-SNAPSHOT'
    guavaVersion = '20.0'
    playServicesVersion = '9.0.1'

    enableCrashlytics = true
}
```

**//Gradle App**

```
apply plugin: "com.android.application"
//apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'io.fabric'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    flavorDimensions "default"
    buildToolsVersion rootProject.ext.buildToolsVersion
        defaultConfig {
        applicationId "com.my_package"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName
        multiDexEnabled true

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }


    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    // Build-in class shrinker and multidex are not supported yet.
    // Crashlytics not support shrinker with proguard and multidex
    // Uses new built-in shrinker http://tools.android.com/tech-docs/new-build-system/built-in-shrinker
    buildTypes {
        debug {
//            minifyEnabled true
//            useProguard false
        }
        release {
//            minifyEnabled true
//            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            testProguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguardTest-rules.pro'

            applicationVariants.all { variant ->
                variant.outputs.all { output ->
                    outputFileName = "App-v${variant.versionName}-v${variant.versionCode}.apk"
                    variant.variantData.variantConfiguration.javaCompileOptions.annotationProcessorOptions.arguments =
                            ['androidManifestFile': variant.outputs[0]?.processResources?.manifestFile?.absolutePath]
                }

            }
        }

    }

    /**
     * Use field "BASE_URL_OPERATIONAL" to declare server url. NOTE: NEVER UTILIZE FINAL URL SEPARATOR "/".
     */
    productFlavors {
        qa {
            dimension "default"
            signingConfig signingConfigs.debug
            buildConfigField "String", "BASE_URL_OPERATIONAL", '"URL"'
            applicationIdSuffix ".qa"
        }
        dev {
            dimension "default"
            signingConfig signingConfigs.debug
            buildConfigField "String", "BASE_URL_OPERATIONAL", '"URL"'
            applicationIdSuffix ".dev"
        }
        acceptance {
            dimension "default"
            signingConfig signingConfigs.debug
            buildConfigField "String", "BASE_URL_OPERATIONAL", '"URL"'
            applicationIdSuffix ".accept"
        }
        production {
            dimension "default"
            signingConfig signingConfigs.release
            buildConfigField "String", "BASE_URL_OPERATIONAL", '"URL"'
        }
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/license.txt'
    }


}

/*
 Dependency versions are defined in the top level build.gradle file. This helps keeping track of
 all versions in a single place. This improves readability and helps managing project complexity.
 */
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    // Dependencies for local unit tests
    testCompile "junit:junit:$rootProject.ext.junitVersion"
    testCompile "org.mockito:mockito-all:$rootProject.ext.mockitoVersion"
    testCompile "org.hamcrest:hamcrest-all:$rootProject.ext.hamcrestVersion"
    testCompile 'org.robolectric:robolectric:3.2.2'

    // Android Testing Support Library's runner and rules
    androidTestCompile "com.android.support:support-annotations:$rootProject.ext.supportLibraryVersion"
    androidTestCompile "com.android.support.test:runner:$rootProject.ext.runnerVersion"
    androidTestCompile "com.android.support.test:rules:$rootProject.ext.rulesVersion"

    //    androidTestCompile 'com.android.support.test.uiautomator:uiautomator-v18:2.1.2'
    androidTestCompile "com.android.support.test.espresso:espresso-core:$rootProject.ext.espressoVersion"

    // App's dependencies, including frameworks
    implementation "com.android.support:appcompat-v7:$rootProject.ext.supportLibraryVersion"
    implementation "com.android.support:design:$rootProject.ext.supportLibraryVersion"
    implementation "com.android.support:cardview-v7:$rootProject.ext.supportLibraryVersion"
    implementation "com.android.support:recyclerview-v7:$rootProject.ext.supportLibraryVersion"
    implementation "com.android.support:gridlayout-v7:$rootProject.ext.supportLibraryVersion"
    implementation "com.android.support:support-annotations:$rootProject.ext.supportLibraryVersion"
    implementation "com.android.support:support-vector-drawable:$rootProject.ext.supportLibraryVersion"
    implementation "com.android.support:support-v4:$rootProject.ext.supportLibraryVersion"
    implementation "com.android.support:customtabs:$rootProject.ext.supportLibraryVersion"

    //implementation 'com.android.support.constraint:constraint-layout:1.0.0-alpha2'
    implementation "com.google.android.gms:play-services-analytics:$rootProject.ext.playServicesVersion"
    implementation "com.google.android.gms:play-services-gcm:$rootProject.ext.playServicesVersion"
    implementation 'com.evernote:android-job:1.1.6'
    implementation 'org.springframework.android:spring-android-rest-template:2.0.0.M3'
    implementation 'com.google.code.gson:gson:2.8.0'
    implementation 'org.jsoup:jsoup:1.9.2'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.github.bumptech.glide:glide:3.7.0'
    implementation 'com.squareup.okhttp:okhttp:2.7.5'
    implementation 'com.squareup.okhttp:okhttp-urlconnection:2.7.5'
    implementation 'com.google.code.ksoap2-android:ksoap2-android:3.6.0'
    implementation "com.google.guava:guava:$rootProject.ext.guavaVersion"
    implementation 'org.apache.commons:commons-lang3:3.6'
    implementation 'org.apache.commons:commons-collections4:4.1'
    implementation 'com.viewpagerindicator:library:2.4.1@aar'
    implementation 'com.ToxicBakery.viewpager.transforms:view-pager-transforms:1.2.32@aar'
    implementation 'com.github.chrisbanes:PhotoView:1.2.6'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.0.1'
    implementation 'com.bignerdranch.android:expandablerecyclerview:2.1.1'
    implementation 'me.leolin:ShortcutBadger:1.1.10@aar'
    implementation('cn.trinea.android.view.autoscrollviewpager:android-auto-scroll-view-pager:1.1.2') {
        exclude module: 'support-v4'
    }

    // Resolve conflicts between main and test APK:
    implementation 'com.android.support:multidex:1.0.2'

    // App notations dependencies
    annotationProcessor "org.androidannotations:androidannotations:$rootProject.ext.aaVersion"
    implementation "org.androidannotations:androidannotations-api:$rootProject.ext.aaVersion"

    annotationProcessor "org.androidannotations:rest-spring:$rootProject.ext.aaVersion"
    implementation "org.androidannotations:rest-spring-api:$rootProject.ext.aaVersion"

    annotationProcessor 'org.projectlombok:lombok:1.16.18'
    implementation 'org.projectlombok:lombok:1.16.18'

    // App analises depencencies
    implementation('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
    implementation('com.crashlytics.sdk.android:crashlytics-ndk:1.1.2@aar') {
        transitive = true;
    }
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:1.5.4'
    debugImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.5.4'
    androidTestImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.5.4'
    implementation 'jp.wasabeef:takt:1.0.3'
}

//apt {
//    arguments {
//        androidManifestFile variant.outputs[0]?.processResources?.manifestFile
//        resourcePackageName android.defaultConfig.applicationId
//    }
//}

crashlytics {
    enableNdk true
    androidNdkOut 'src/main/obj'
    androidNdkLibsOut 'src/main/libs'
}

configurations.all {
   resolutionStrategy {
       force "com.android.support:support-annotations:$rootProject.ext.supportLibraryVersion"
    }
}
```

**Comment by dodgex** [comment] 2017-11-27 06:50
At the moment I can't see an issue with your build config. Can you test if the 4.4.0 release works?

What are there errors in build log? e.g. when you compile from command line?

**Comment by JDSCaram** [comment] 2017-11-27 09:49
my first attempt was to use version 4.4.0, I just put it to 4.5.0-SNAPSHOT as I saw in the git example
I already tested in versions 4.3.0 / 4.4.0 / 4.5.0-SNAPSHOT and none worked

In the log all the Activities and Fragment 
"error: cannot find symbol class .... "

**Comment by WonderCsabo** [comment] 2017-11-29 09:42
@JDSCaram this part should be removed:

```groovy
variant.variantData.variantConfiguration.javaCompileOptions.annotationProcessorOptions.arguments =
                            ['androidManifestFile': variant.outputs[0]?.processResources?.manifestFile?.absolutePath]
```

And add this:
```groovy
android {
    // ...

    defaultConfig {
        // ...

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["resourcePackageName": android.defaultConfig.applicationId]
            }
        }
    }
}
```

Check out the [wiki](https://github.com/androidannotations/androidannotations/wiki/Building-Project-Gradle).

**Comment by JDSCaram** [comment] 2017-11-29 12:09
I changed my gradle with above example however it still does not run (link example image)
https://imgur.com/4d7y3rG

```
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    flavorDimensions "default"
    buildToolsVersion rootProject.ext.buildToolsVersion
    defaultConfig {
        applicationId "my_packge"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName
        multiDexEnabled true

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["resourcePackageName": android.defaultConfig.applicationId]
            }
        }
    }
   ...

```

**Comment by WonderCsabo** [comment] 2017-11-29 12:26
Please paste the `androidannotations.log` file.

**Comment by JDSCaram** [comment] 2017-11-29 13:37
Below the `androidannotations.log`

```
09:44:57.507 [Task worker for ':' Thread 2] ERROR o.a.i.p.ModelValidator:74 - org.androidannotations.annotations.EApplication can only be used on an element that extends android.app.Application
09:44:57.508 [Task worker for ':' Thread 2] WARN  o.a.i.p.ModelValidator:84 - Element com.my_package invalidated by EApplicationHandler
```

My Application

```
@EApplication
public class OperationalApp extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        initialize();
    }

    private void initialize() {
        JobManager.create(this).addJobCreator(new OperationalJobCreator(this));
    }
}
```

AndroidManifest
```
<application
        android:name=".OperationalApp_"
        android:allowBackup="false"
        android:configChanges="orientation|screenSize"
        android:hardwareAccelerated="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"> 
   ...

```

**Comment by WonderCsabo** [comment] 2017-11-29 14:23
Are you sure your are extending the correct `Application` class? Also, try to search for other uses `@EApplication`. I am pretty sure you are using it wrong somewhere.

**Comment by JDSCaram** [comment] 2017-11-29 15:45
I am extending " android.app.Application;"

```
import android.app.Application;
import com.evernote.android.job.JobManager;
import com.luxfacta.abinbev.operationalexcellence.job.OperationalJobCreator;
import org.androidannotations.annotations.EApplication;

@EApplication
public class OperationalApp extends Application { }
```

I searched the entire project for the use of OperationalApp_.class and did not find, just only reference OperationalApp.class
So I removed from AndroidManisfest the OperationalApp_ and left the normal application
I cleaned the project and put it to run again, the error of above link continues but the file **androidannotations.log** is empty now.

**Comment by WonderCsabo** [comment] 2017-11-29 15:58
If you share the project i can take a look.

**Comment by JDSCaram** [comment] 2017-11-29 16:28
I would very much like to be able to make the project available for you to look at, but the company does not allow
I have that rename all reference just to post here, due contractual matters

At the moment I'm using in production the following version and it's working. (below)
   ```
minSdkVersion = 16
   targetSdkVersion = 24
   compileSdkVersion = 24
   buildToolsVersion = '24 .0.3 '
   androidAnnotationsVersion = '4.3.0'

  dependencies {
         // replace with the current version of the Android plugin
         classpath 'com.android.tools.build:gradle:3.0.1'
         classpath 'com.google.gms: google-services: 3.1.0'
         classpath 'io.fabric.tools:gradle:1.24.4'
     }

distributionUrl = https \: //services.gradle.org/distributions/gradle-3.5-all.zip
```

**Comment by Gnanaoly** [comment] 2017-12-08 05:50
I am also facing same kind of issue.  For me there is no error reason showing.  The code not generated.

**Comment by crystalzhaoluoyang** [comment] 2017-12-12 09:48
4.4.0works for me !
![annotation_build](https://user-images.githubusercontent.com/24367697/33877854-a913eb02-df64-11e7-94b7-f06efd2e86a4.png)

**Comment by nttgithubntt** [comment] 2017-12-14 02:34
you reference https://github.com/androidannotations/androidannotations/issues/2079

**Comment by latrevisani** [comment] 2018-02-28 20:42
I was having the same issue. And searching for similar issues, I faced:
https://stackoverflow.com/questions/36685423/android-annotation-upgrade-to-4-0-0-build-error
So I replaced all my:
@Extra List<T>
by:
@Extra ArrayList<T>
And all those cannot find symbol _ errors were gone.

**Comment by swatisoni-ewebcore** [comment] 2018-08-30 11:19
I'm facing the same issue with API 25 , 26 and 27

**Comment by mdumrauf** [comment] 2018-10-12 05:17
Any news on this? I'm facing the same error and can't configure build variants in my project.

**Comment by swatisoni-ewebcore** [comment] 2018-10-12 06:14
> Any news on this? I'm facing the same error and can't configure build variants in my project. I'm using AA 4.4.0

@mdumrauf , Android Annotation is not supportive for API 26 and above. I didn't get solution after wasting a week. At last i replaced Android Annotations by butterKnife and some default methods of Android.

**Comment by dodgex** [comment] 2018-10-17 08:41
@mdumrauf Do you use Parceler? The given stacktrace is not related to android annotations.  as you can see the crash comes from `InstantRunTransform`. does it work when you do not use instant run?

for me this looks like a issue with the android gradle build plugin

**Comment by mdumrauf** [comment] 2018-10-17 20:12
@dodgex I do. That was it, thanks!

**Comment by dodgex** [comment] 2018-10-18 12:29
If you can reproduce this issue in a small project, you should open an issue in the google issue tracker for Instant run so they can fix that. :)

**Comment by dodgex** [comment] 2018-10-21 13:15
I'll close this issue. With 4.5.x many of the issues that classes where not generated are fixed and the issue has already been "reused" for other issues.

if someone still has a similar issue, please create a new one

**Closed by dodgex** 2018-10-21 13:15 UTC
