### ISSUE TITLE
It's extremely hard to find an error

### ISSUE THREAD

**Issue by yuiopt** [androidannotations/androidannotations#1892] opened 2016-11-11 15:25 UTC
It's really hard to find an error of view id,I have to open all of the activity or fragment classes to see where the really error is,are there any fast ways to find real errors rather than the output classes with "_" added after actiivty or fragment?

**Comment by WonderCsabo** [comment] 2016-11-11 16:10
The error will be in the compiler output (possibly buried between hundreds of could not find symbol errors). Also, it is possible that you should [disable the limit of the error count](https://github.com/androidannotations/androidannotations/issues/1868#issuecomment-252416119).

**Comment by yuiopt** [comment] 2016-11-11 16:33
@WonderCsabo Thanks for help,I have solved this little error caused by "@ViewById" where id does not exist.I have to say I have opened all the Activity and Fragment classes  ,and have gone  through for twice, as well as all the xml layout files.Luckily and finally , it's done. But I have to say it really did not locate where the error was, it just printed hundreds of lines "ERROR:CANNOT FIND SYMBOL import xxx.xxx.xxx.SomeActivity_",hope this can help to improve our library.

**Comment by rickbijkerk** [comment] 2016-11-16 14:05
it normally is the last line in the log which shows the cause of the error

**Closed** 2016-11-23 22:42 UTC
