### ISSUE TITLE
Unable to build project with @Pref in @EBean with kapt

### ISSUE THREAD

**Issue by WeaponMan** [androidannotations/androidannotations#1925] opened 2016-12-20 21:34 UTC
**AndroidAnnotations version**: 4.2.0
**Android compile SDK version**: 25
**Annotated code**:
```java
@SharedPref(SharedPref.Scope.APPLICATION_DEFAULT)
interface TestPref {
    fun test(): String
}

@EBean
open class TestBean {
    @Pref lateinit open var test: TestPref_
}
```
**Kotlin version**: 1.0.5-3 (kapt2)

I am unable to build this annotated code, but in java version of this builds fine.
Annotating only activity/fragment is also fine only on Ebean this code end with unresolved reference on TestPref_.
```
error: org.androidannotations.annotations.sharedpreferences.Pref can only be used on an element that extends org.androidannotations.api.sharedpreferences.SharedPreferencesHelper
warning: Element test invalidated by PrefHandler
```

**Comment by WonderCsabo** [comment] 2016-12-30 11:04
@WeaponMan can you create an example project? You could extend our [kotlin sample](https://github.com/androidannotations/androidannotations/tree/develop/examples/kotlin). I am aware of this issue, but i think we do not do anything wrong here. Maybe we should report it to kapt/kotlin developers.

**Comment by WeaponMan** [comment] 2016-12-30 11:43
Ok, no problem. I will create a PR.
I tested this with new kapt3 from 1.0.6-eap-121, but same result. 
I will stick with only java for some time.

**Comment by WeaponMan** [comment] 2016-12-30 12:44
#1928

**Comment by WeaponMan** [comment] 2016-12-31 16:08
Created new [branch](https://github.com/WeaponMan/androidannotations/tree/non_working_kapt_code) for non compilable code with kapt3.

**Comment by WonderCsabo** [comment] 2017-01-26 23:20
@WeaponMan I got to the bottom of this, and i opened a [ticket](https://youtrack.jetbrains.com/issue/KT-16006) against the Kotlin compiler.

**Comment by WonderCsabo** [comment] 2017-02-02 08:59
Fixed as of Kotlin 1.1.0-beta-17.

**Closed by WonderCsabo** 2017-02-02 08:59 UTC

**Comment by kristynarehovicova** [comment] 2017-08-16 16:51
I am using latest version and it not working anymore.

**AndroidAnnotations version:** 4.3.1
**Android compile SDK version:** 26
**Kotlin version:** 1.1.4

**Annotated Code:**
```
@SharedPref(SharedPref.Scope.APPLICATION_DEFAULT)
interface UserPrefs {

    @DefaultString("")
    fun username(): String

    @DefaultString("")
    fun firstname(): String

    @DefaultString("")
    fun lastname(): String

    @DefaultString("Unknown")
    fun role(): String

    @DefaultString("")
    fun token(): String

    @DefaultString("[]")
    fun dashboard(): String
}
```

I am using it in both activity and fragment:
```
@Pref
lateinit var userPrefs: UserPrefs_
```

With the error like origin question:
```
11:45:06.23 [RMI TCP Connection(124)-127.0.0.1] ERROR o.a.i.p.ModelValidator:77 - org.androidannotations.annotations.sharedpreferences.Pref can only be used on an element that extends org.androidannotations.api.sharedpreferences.SharedPreferencesHelper
11:45:06.23 [RMI TCP Connection(124)-127.0.0.1] WARN  o.a.i.p.ModelValidator:88 - Element userPrefs invalidated by PrefHandler
```

Is there something new in AA how to use Pref in Kotlin?

**Comment by WeaponMan** [comment] 2017-08-16 18:19
Quick tested solution is to change String to String?.
I tried this second ago with gradle 4.1-rc

**Comment by kristynarehovicova** [comment] 2017-08-16 19:18
@WeaponMan thats strange. Using `?` does nothing to me. I am also using gradle 4.1-rc. o you have the same AA and kotlin version also?

**Comment by WeaponMan** [comment] 2017-08-16 19:54
Simply add this block to your application level build.gradle file:
```groovy 
kapt {
    correctErrorTypes = true
}
```
It will compile fine.

**Comment by WeaponMan** [comment] 2017-08-16 19:59
Taking that back... I used your class in @EBean same result so far.

**Comment by WeaponMan** [comment] 2017-08-16 20:08
I simply forgot to import the generated class. (ssh with nano as editor no auto-imports)
Yep, its successfully compiling now.

**Comment by kristynarehovicova** [comment] 2017-08-16 20:35
Great! It is working now. Thanks for help.

**Comment by Aqua-Ye** [comment] 2019-09-13 15:48
I'm using the `@Pref` annotation in an `@EBean` class, but when I try to access the pref variable, it says it is not initialized:

```
@EBean(scope = EBean.Scope.Singleton)
class PrefsHelper {

    @Pref
    lateinit var sharedPref: MySharedPrefs_

    fun lastActionTime(): Long {
        return sharedPref.last_action_time().getOr(0L)
    }
}
```

any idea why?

**Comment by WonderCsabo** [comment] 2019-09-13 16:09
Are you using the latest Kotlin Gradle plugin?

**Comment by Aqua-Ye** [comment] 2019-09-13 16:22
> Are you using the latest Kotlin Gradle plugin?

`1.3.50`

**Comment by WonderCsabo** [comment] 2019-09-13 16:51
I think you have to add

```groovy
kapt {
            correctErrorTypes = true
        }
```

In your build.gradle

**Comment by Aqua-Ye** [comment] 2019-09-14 13:03
> I think you have to add
> 
> ```groovy
> kapt {
>             correctErrorTypes = true
>         }
> ```
> 
> In your build.gradle

Already did, it let me compile, but the variable was still uninitialized

**Comment by WonderCsabo** [comment] 2019-09-14 16:45
Are you using the generated PrefHelper_ class?

**Comment by Aqua-Ye** [comment] 2019-09-16 08:28
> Are you using the generated PrefHelper_ class?

Yes, it's being used in another `@EBean` class.
```
@EBean(scope = EBean.Scope.Singleton)
class KMicroServicesUtils {

    @Bean
    lateinit var prefsHelper: PrefsHelper

}
```

**Comment by WonderCsabo** [comment] 2019-09-16 08:31
If you create a small project which can reproduce the problem, i can take a look.

**Comment by Aqua-Ye** [comment] 2019-09-16 10:22
> If you create a small project which can reproduce the problem, i can take a look.

I can't reproduce the bug with a small project :/

What happens in my project is, nothing is generated in the `PrefsHelpers_.init_` method.

```
public final class PrefsHelper_
    extends PrefsHelper
{
    private Context context_;
    private static PrefsHelper_ instance_;

    private PrefsHelper_(Context context) {
        context_ = context;
    }

    public static PrefsHelper_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new PrefsHelper_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }
}
```

While on the small test project, it is.

```
public final class PrefsHelper_
    extends PrefsHelper
{
    private Context context_;
    private static PrefsHelper_ instance_;

    private PrefsHelper_(Context context) {
        context_ = context;
    }

    public static PrefsHelper_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new PrefsHelper_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
        this.userPrefs = new UserPrefs_(context_);
    }
}
```

Both classes are defined the same:

```
@EBean(scope = EBean.Scope.Singleton)
class PrefsHelper {

    @Pref
    lateinit var userPrefs: UserPrefs_

    var lastActionTime: Long
        get() = userPrefs.last_action_time().get()
        set(value) = userPrefs.edit().last_action_time().put(value).apply()

}
```

**Comment by Aqua-Ye** [comment] 2019-09-20 10:15
@WonderCsabo ok so in fact it was just a gradle caching issue. Sorry!

**Comment by ddekanski** [comment] 2019-11-06 17:10
I had the same issue, though having `correctErrorTypes = true` in `build.gradle`. I investigated that upgrading `com.jakewharton.timber:timber` from 4.7.0 to 4.7.1 was the culprit. @Aqua-Ye you can check if that was the cause in your case as well. @WonderCsabo I think it's worth looking at `timber` commits since 4.7.0 to narrow down the problem (https://github.com/JakeWharton/timber/releases/tag/4.7.0).
