### ISSUE TITLE
Error:(134, 36) 错误: 不兼容的类型: PullToRefreshListView无法转换为AdapterView<?>

### ISSUE THREAD

**Issue by AllenCoder** [androidannotations/androidannotations#1871] opened 2016-10-09 04:05 UTC
```java
   if (this.expandList!= null) {
            ((AdapterView<?> ) this.expandList).setOnItemClickListener(new OnItemClickListener() {

                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    AllIndexAssetActivity_.this.itemOnclick(position);
                }
            }
            );
        }
```

when  i  upgrade 4.1.0 FAILURE: Build failed with an exception. 

PullToRefreshListView  cannot transform   AdapterView

**Comment by AllenCoder** [comment] 2016-10-09 04:06
this is 4.0.0

```java
  @Override
    public void onViewChanged(HasViews hasViews) {
        this.expandList = ((PullToRefreshListView) hasViews.findViewById(R.id.expand_list));
        if (this.expandList!= null) {
            this.expandList.setOnItemClickListener(new OnItemClickListener() {

                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    FixedProductFragement_.this.itemClick(position);
                }
            }
            );
        }
        afterView();
    }
```

**Comment by dodgex** [comment] 2016-10-10 08:11
duplicate of https://github.com/androidannotations/androidannotations/issues/1845

I'll close this in favour ot the previous issue.

**Closed by dodgex** 2016-10-10 08:11 UTC
