### ISSUE TITLE
Crash during make project: IllegalArgumentException: The expression must be false but it is not: trying to create the same field twice: fragmentSupport_

### ISSUE THREAD

**Issue by Namnodorel** [androidannotations/androidannotations#2168] opened 2018-10-13 13:05 UTC
**AndroidAnnotations version**: 4.5.0

**Android compile SDK version**: 28

**Annotated code**:
```java
@EBean
public class MyClass{
    //Doesn't use any AA features, it's just annotated so it can be injected somewhere else as an attribute
    public MyClass(){
        //...
    }
    //...
}
```

**Stacktrace in case of AA crash**:

```
error: Something went wrong: Unexpected error in AndroidAnnotations 4.5.0!
You should check if there is already an issue about it on https://github.com/androidannotations/androidannotations/search?q=java.lang.IllegalArgumentException&type=Issues
If none exists, please open a new one with the following content and tell us if you can reproduce it or not. Don't forget to give us as much information as you can (like parts of your code in failure).
Java version: javac 1.8.0_92
Javac processors options: androidManifestFile=app\build\intermediates\merged_manifests\debug\AndroidManifest.xml
Stacktrace: java.lang.IllegalArgumentException: The expression must be false but it is not: trying to create the same field twice: fragmentSupport_
at com.helger.jcodemodel.util.JCValueEnforcer.isFalse(JCValueEnforcer.java:144)
at com.helger.jcodemodel.JDefinedClass.field(JDefinedClass.java:402)
at com.helger.jcodemodel.JDefinedClass.field(JDefinedClass.java:375)
at org.androidannotations.internal.core.helper.ActivityIntentBuilder.addFragmentConstructor(ActivityIntentBuilder.java:116)
at org.androidannotations.internal.core.helper.ActivityIntentBuilder.createAdditionalConstructor(ActivityIntentBuilder.java:111)
at org.androidannotations.internal.core.helper.ActivityIntentBuilder.build(ActivityIntentBuilder.java:71)
at org.androidannotations.holder.EActivityHolder.<init>(EActivityHolder.java:115)
at org.androidannotations.internal.core.handler.EActivityHandler.createGeneratedClassHolder(EActivityHandler.java:47)
at org.androidannotations.internal.core.handler.EActivityHandler.createGeneratedClassHolder(EActivityHandler.java:39)
at org.androidannotations.internal.process.ModelProcessor.generateElements(ModelProcessor.java:203)
at org.androidannotations.internal.process.ModelProcessor.process(ModelProcessor.java:74)
at org.androidannotations.internal.AndroidAnnotationProcessor.processAnnotations(AndroidAnnotationProcessor.java:224)
at org.androidannotations.internal.AndroidAnnotationProcessor.processThrowing(AndroidAnnotationProcessor.java:176)
at org.androidannotations.internal.AndroidAnnotationProcessor.process(AndroidAnnotationProcessor.java:126)
at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
at org.gradle.api.internal.tasks.compile.processing.NonIncrementalProcessor.process(NonIncrementalProcessor.java:45)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
at com.sun.tools.javac.main.Main.compile(Main.java:523)
at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:89)
at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:100)
at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:49)
at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:35)
at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:39)
at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:27)
at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:153)
at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:138)
at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:110)
at com.android.build.gradle.tasks.AndroidJavaCompile.compile(AndroidJavaCompile.kt:235)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by dodgex** [comment] 2018-10-13 13:12
Hey @Namnodorel ,

it looks like this issue is due to having both `android.support.v4.app.Fragment` and  `androidx.fragment.app.Fragment` on classpath.

can you confirm that you have both the "old" support library and Android X in your project?

**Comment by Namnodorel** [comment] 2018-10-13 13:17
@dodgex No, at least not that I am aware of. I auto-migrated the whole project to AndroidX as soon as that was possible, and the old Support Library is no longer in `build.gradle`.

**Comment by dodgex** [comment] 2018-10-13 14:31
Hey @Namnodorel 

a PR for the issue is up. As there are only snapshots after it is merged into develop and the PR still needs to be reviewed by @WonderCsabo you could test it by checking out my branch and installing the snapshot locally.

would be awesome if you have a chance to test that and give some feedback if it works or not in the PR.

**Comment by Namnodorel** [comment] 2018-10-13 15:11
First of all, thank you for the quick fix! Unfortunaley, building AA appears to require more than simply cloning + hitting make... And I don't have the time right now to configure something for every new thing the build complains about. JitPack is apparently also not equipped to handle AA - are the artifacts from the CI build available somewhere? Since I'm usually on GitLab, I'm not very used to Travis.

**Comment by dodgex** [comment] 2018-10-13 16:09
Unfortunately there are no snapshots for PR and travis also does not offer any artifact downloads.

To build the project it should be enough to clone, and `./mvnw install`  when you have `ANDROID_HOME` correctly set and having build-tools + Android SDK 16 installed.

Csaba plans to review the PR this evening, after it is merged there are snapshots available. :)

**Closed** 2018-10-13 22:17 UTC

**Comment by dodgex** [comment] 2018-10-14 06:46
@Namnodorel could you please test the latest snapshot? I plan to release 4.5.1 this evening and it would be awesome to know if it works for you before doing that :)

**Comment by Namnodorel** [comment] 2018-10-14 07:40
Yup, the error is gone using `4.6.0-SNAPSHOT`

**Comment by dodgex** [comment] 2018-10-14 07:50
Awesome, thanks for testing =)

**Comment by dodgex** [comment] 2018-10-14 09:04
I just released AA 4.5.1 and it should be available soon on maven central.
